Input field for "Reason for Red"
WildAid/o-fish-ios pull request #205
Opened 2020-08-20 12:12 UTC by MykytaKiriushyn

2020-08-20 12:42 UTC, akaktus commented on o-fish-ios/Views/ReportFlow/Risk/RiskView.swift
> +                        InputField(title: "Reason for red", text: self.$report.inspection.summary.safetyLevel.redReason)
Need add this key in localization "Reason for red"

2020-08-26 08:02 UTC, am-MongoDB requested changes
The comment from Artem needs to be addressed.

Changes to the model need to be coordinated between iOS, Android, web, Realm and the existing documents in Atlas so that Realm Sync continues to work.

Rather than having `redReason` and `amberReason`, it would be better to have a single field called `reason`.

As a stop gap, could just use `amberReason` for both red and amber *but* need to keep open an issue to rename the field in the schema.

2020-08-31 14:01 UTC, akaktus approved these changes
LGTM

2020-09-01 14:14 UTC, am-MongoDB commented
@MykytaKiriushyn Note that this is still waiting for the review comments to be addressed

2020-09-02 15:12 UTC, am-MongoDB approved these changes

2020-09-02 15:12 UTC, merged