Store country code in Vessel Information page
WildAid/o-fish-ios pull request #336
Opened 2020-09-30 19:27 UTC by nugmanoff

Hey there! I am happy to contribute to your repository as part of Hacktoberfest 2020

This PR Closes #332 

Some rationale behind my changes:

• I renamed `image` variable to `code` in `CountryPickerData` because it is quite because previous name is quite ambiguous and misleading per se. So now variable `code` basically describes what kind of value it holds (short country code). `image` variable was used only once when magically retrieving country emoji, and even in that context it makes more sense to write function like `flag(for countryCode: String)`
• This change basically enabled me to retrieve `$0.code` directly and assign it to `vessel.nationality` in binding closure without introducing ambiguity (it'd be less obvious if it was `self.vessel.nationality = $0.image`, but it'd have worked the same way it does now).
• Also I fixed name of the `CountryPickerView.swift` file.

2020-10-01 01:23 UTC, Sheeri commented
Hi @nugmanoff - Thanks so much for this PR! We appreciate that you gave your rationale for the things we might say "why did they do that?"

Our team will fully review this by this time on Monday (three business days). Until then, please feel free to work on another issue.

2020-10-01 13:41 UTC, o-fish-wildaid commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review PRs](https://trello.com/c/QKVtiwN0/372-review-prs)

2020-10-01 14:03 UTC, am-MongoDB requested changes
What's in the PR is good, but there's one another change needed.

When you view an existing report, the country should be mapped back from the (stored) code to the full country name – this is what the view currently looks like, but `GB` should actually be displayed as `United Kingdom`
![image](https://user-images.githubusercontent.com/14197449/94819494-3ff8af80-03f7-11eb-9df2-e325546a978f.png)

2020-10-01 14:30 UTC, nugmanoff commented
@am-MongoDB thanks for pointing that one out, I missed that! Can you please check the updated revision?

2020-10-01 17:52 UTC, am-MongoDB requested changes
I tested the latest and the report view seems correct, but it looks like 140 older commits have been dragged into this PR
![image](https://user-images.githubusercontent.com/14197449/94845180-3c752080-0417-11eb-98eb-5b320c421f51.png)

Could you please try to clean up the PR so that it only contains your changes?

Thanks, Andrew.

2020-10-01 20:07 UTC, nugmanoff commented
@am-MongoDB  I tried to clean up the PR, but unfortunately I wasn't able to do that. I have no idea how to do it in this context, can you please give me some ideas on how to remove this unneeded commits from the PR?

2020-10-01 22:25 UTC, am-MongoDB commented
@nugmanoff I'm not a git-guru and so I always keep it simple.

If you can't get your current fork into line, then:
[ ] Take a copy of the files you've changed
[ ] Create a clean fork
[ ] Reapply your changes
[ ] Create a new PR, include `#fixes #332` and a  reference your original PR in the description

Andrew.

2020-10-02 03:47 UTC, nugmanoff commented
@am-MongoDB thanks! but I think I've already fixed the issues

2020-10-02 09:30 UTC, am-MongoDB approved these changes

2020-10-02 09:31 UTC, merged

2020-10-02 09:31 UTC, am-MongoDB commented
Thanks @nugmanoff PR merged - thanks!