347 Dark Mode initial implementation
WildAid/o-fish-ios pull request #361
Opened 2020-10-13 00:30 UTC by bladebunny

## Related Issue

Fixes #347
Changing the mode on the profile page now changes the color scheme. I have not changed all colors. Some views will auto-change based on the system colors. But we will need to go through and ensure views are using a correct color set color that is based on the design instead if relying on defaults.

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [x] My change adds new text and requires a change to translations.
- [x] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 
I've backed out my additional localization stuff and this now only uses pre-existing loc set-up.
This PR can be closed once it passes merge checks and review.

* **Optional: Add any relevant screenshots here**

2020-10-13 08:35 UTC, o-fish-wildaid commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review PRs](https://trello.com/c/hsyA27BP/423-review-prs)

2020-10-13 12:13 UTC, am-MongoDB requested changes
Could you please merge with the latest `main` when you make the changes (as it contains a fix for a bug that's preventing me from testing this PR.

Thanks.

2020-10-13 12:13 UTC, am-MongoDB commented on o-fish-ios/ViewModel/User/UserSettings.swift
> +import Foundation
Remove?

2020-10-13 17:27 UTC, bladebunny commented
Feedback incorporated and merge conflict in project file fixed.

2020-10-13 17:27 UTC, bladebunny commented on o-fish-ios/ViewModel/User/UserSettings.swift
> +    static let showDarkMode = "showDarkMode"
Done

2020-10-13 17:27 UTC, bladebunny commented on o-fish-ios/Helpers/String+Extensions.swift
> +}
I was using this earlier - removed now.

2020-10-13 17:28 UTC, bladebunny commented on o-fish-ios/Helpers/String+Extensions.swift
> +    }
Removed.  Makes nil/empty checking strings easier but removed.

2020-10-13 17:28 UTC, bladebunny commented on o-fish-ios/ViewModel/User/UserSettings.swift
> +import Foundation
Need to keep this.

2020-10-14 08:48 UTC, am-MongoDB commented on o-fish-ios/Helpers/String+Extensions.swift
> +    }
Thanks – I didn't see it used anywhere

2020-10-14 09:16 UTC, am-MongoDB requested changes
Still can't test, as this has been rebased onto `main`, but then the effects of https://github.com/WildAid/o-fish-ios/pull/363 have been undone (e.g. `DoneTextField.swift` has been added back in)

2020-10-14 12:49 UTC, bladebunny commented
Sorry. I'll take a look. When I pulled there was a merged conflict that looked like it was adding DoneTextField. Will see if I can sort it out.

2020-10-16 08:32 UTC, am-MongoDB requested changes
It's still undoing part of the fix that went into `main` - e.g., these changes to the README

2020-10-16 08:34 UTC, am-MongoDB commented
> It's still undoing part of the fix that went into `main` - e.g., these changes to the README

@bladebunny - actually, looks like the README is the only thing that needs backing out, so I should be able to test this version. Thanks.

2020-10-16 09:02 UTC, am-MongoDB commented
I'll merge as-is and then fix the README afterwards

2020-10-16 09:03 UTC, merged