Add @ObservedObject attachments to respond to attachment changes.
WildAid/o-fish-ios pull request #367
Opened 2020-10-15 02:41 UTC by coltonlemmon

## Related Issue

Fixes # 247

## Checklist:

- [x ] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x ] I linked an issue in the previous section
- [x ] I have commented on the linked issue
- [x ] I was assigned the linked issue (not required)
- [x ] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 
Modifying attachments wasn't updating the correct view because the EMSInputView was not observing AttachmentsViewModel directly. There may be a better way to do this that I am unaware of.

Also note that there is a separate issue when attempting to delete a note. I'm going to create an issue for this.

* **Optional: Add any relevant screenshots here**

2020-10-16 10:22 UTC, am-MongoDB commented
It looks like the problem is wider than just notes for EMS - impacts other views too

2020-10-16 10:47 UTC, am-MongoDB requested changes

2020-10-16 10:47 UTC, am-MongoDB commented on o-fish-ios.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = P3B9MPU7J2;
Don't make this change

2020-10-16 10:47 UTC, am-MongoDB commented on o-fish-ios.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = P3B9MPU7J2;
Don't make this change

2020-10-16 10:47 UTC, am-MongoDB commented on o-fish-ios/Views/ReportFlow/Vessel/EMSInputView.swift
> +    @ObservedObject var attachments: AttachmentsViewModel
This problem isn't limited to just this view - it's anywhere that a note is attached. Would be good to find a solution that's in `AddAttachmentsButton` or lower

2020-10-20 10:02 UTC, am-MongoDB commented
I think I may have a solution to this as part of working on https://github.com/WildAid/o-fish-ios/issues/368

2020-10-20 13:40 UTC, am-MongoDB commented
This has been fixed under https://github.com/WildAid/o-fish-ios/pull/375 along with the crash when deleting notes.

The solution I opted for was to remove the "emptiness" tests surrounding the embedding of `AttachmentView`, as this preventing the AttachmentView being created even after a note was added – this shouldn't be needed if everything in SwiftUI was working as advertised.

Thanks @coltonlemmon for your work on this!

2020-10-20 13:40 UTC, closed without merging

2020-10-26 05:47 UTC, coltonlemmon commented
@am-MongoDB Thats a good solution. I had a hard time understanding what was wrong because it seemed like it should have been working correctly to me. 

If you found this PR helpful would you mind marking it as hacktoberfest-accepted?